# Generated by Django 5.2.14 on 2026-05-28 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=80)),
                ("unit", models.CharField(max_length=20)),
                (
                    "factor_value",
                    models.FloatField(help_text="kg CO2e per unit of activity"),
                ),
                ("source_citation", models.CharField(max_length=200)),
                ("valid_year", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField()),
                ("raw_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP (fuel + procurement)"),
                            ("UTILITY", "Utility (electricity)"),
                            ("TRAVEL", "Travel (flights/hotels/cars)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[
                            (1, "Scope 1 — direct"),
                            (2, "Scope 2 — purchased energy"),
                            (3, "Scope 3 — value chain"),
                        ]
                    ),
                ),
                ("activity_value", models.FloatField()),
                ("activity_unit", models.CharField(max_length=20)),
                ("activity_date", models.DateField()),
                ("co2e_kg", models.FloatField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("CLEAN", "Clean — no issues detected"),
                            ("FLAGGED", "Flagged — needs analyst attention"),
                            ("APPROVED", "Approved — ready for audit"),
                            ("REJECTED", "Rejected — excluded from reporting"),
                        ],
                        default="CLEAN",
                        max_length=16,
                    ),
                ),
                ("flag_reason", models.CharField(blank=True, max_length=255)),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emission_factor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.emissionfactor",
                    ),
                ),
                (
                    "raw_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_records",
                        to="core.rawrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_records",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("EDITED", "Edited"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        max_length=16,
                    ),
                ),
                ("field_changed", models.CharField(blank=True, max_length=80)),
                ("old_value", models.CharField(blank=True, max_length=255)),
                ("new_value", models.CharField(blank=True, max_length=255)),
                ("changed_by", models.CharField(max_length=120)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.TextField(blank=True)),
                (
                    "normalized_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="core.normalizedrecord",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rawrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_records",
                to="core.tenant",
            ),
        ),
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP (fuel + procurement)"),
                            ("UTILITY", "Utility (electricity)"),
                            ("TRAVEL", "Travel (flights/hotels/cars)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_by", models.CharField(max_length=120)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.IntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="core.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="rawrecord",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_records",
                to="core.uploadbatch",
            ),
        ),
    ]
